version: "3"
services:
    pheaktra:
        #image: it for name your image after docker build -t nameyourimages .
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - 3243:3000